development: &dev_settings
  indexed_models:
    - Doc
    - Jurisprudence
    - Page
  html_strip: true
  charset_type: utf-8
  morphology: stem_ru
  sql_query_pre: ["SET NAMES utf8"]
production:
  <<: *dev_settings
test:
  <<: *dev_settings
