development: &dev_settings
  port: 3320
  indexed_models:
    - Doc
    - Jurisprudence
    - Page
  html_strip: true
  charset_type: utf-8
  allow_star: true
  enable_star: true
  min_prefix_len: 0
  min_infix_len: 1
  min_word_len: 1
  charset_table: "0..9, A..Z->a..z, _, a..z, \ U+410..U+42F->U+430..U+44F, U+430..U+44F"
  morphology: 'stem_ru, stem_en'
production:
  <<: *dev_settings
test:
  <<: *dev_settings
