development:
  morphology: stem_ru
  indexed_models:
    - Doc
    - Jurisprudence
    - Page
  html_strip: true
  charset_type: utf-8
production:
  morphology: stem_ru
  indexed_models:
    - Doc
    - Jurisprudence
    - Page
  html_strip: true
  charset_type: utf-8
